language: c++
sudo: false
dist: bionic
os:
- linux
- osx
addons:
  apt:
    packages:
    - libfreetype6-dev
    - libgtest-dev
    - libsdl2-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libswscale-dev
    - libswresample-dev
before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ffmpeg; fi
script:
- python scripts/check_header_guards.py
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then CMAKE_EXTRA_ARGS="-DDOWNLOAD_GTEST=ON -DDEV=ON -DFFMPEG=ON"; fi
- if [ "$TRAVIS_OS_NAME" != "osx" ]; then CMAKE_EXTRA_ARGS="-DGTEST_LIBRARY=../gtest_build/libgtest.a -DGTEST_MAIN_LIBRARY=../gtest_build/libgtest_main.a -DFFMPEG=ON"; mkdir gtest_build; cmake -E chdir gtest_build cmake /usr/src/gtest; cmake --build gtest_build; fi
- mkdir build; cd build
- cmake -Werror=dev -DCMAKE_INSTALL_PREFIX=/usr $CMAKE_EXTRA_ARGS ..
- make everything
- make run_tests
- if [ "$TRAVIS_OS_NAME" != "osx" ]; then make DESTDIR=install install; test -x install/bin/DDNet; test -x install/bin/DDNet-Server; test -d install/bin/data; test -d install/usr/lib; fi
- make package_default
- cd ..; mkdir build_debug; cd build_debug
- cmake -Werror=dev -DCMAKE_BUILD_TYPE=Debug $CMAKE_EXTRA_ARGS ..
- make run_tests
- cd ..
- build/DDNet-Server shutdown
- mkdir DDNet-Demorecorder-"$TRAVIS_OS_NAME"; cp build/DDNet build/DDNet-Server build/config_retrieve build/config_store build/dilate build/map_diff build/map_extract autoexec_server.cfg license.txt storage.cfg DDNet-Demorecorder-"$TRAVIS_OS_NAME"; cp -r data DDNet-Demorecorder-"$TRAVIS_OS_NAME"; tar -cJvf DDNet-Demorecorder-"$TRAVIS_OS_NAME".tar.xz DDNet-Demorecorder-"$TRAVIS_OS_NAME";
env:
  global:
  - CFLAGS="-Wdeclaration-after-statement -Werror"
  - CXXFLAGS="-Werror"
branches:
  except:
  - staging.tmp
  - testing.tmp
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file:
    - ${TRAVIS_BUILD_DIR}/DDNet-Demorecorder-"$TRAVIS_OS_NAME".tar.xz 
  skip_cleanup: true
  draft: true
  on:
    tags: true
